version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: monitoring_postgres
    restart: always
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: evidently
      POSTGRES_PASSWORD: evidently
      POSTGRES_DB: monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
